# Generated by Django 5.2.1 on 2025-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_kg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='areas_en',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='areas_ru',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='about_property_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='about_property_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='address_en',
            field=models.CharField(max_length=133, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='address_ru',
            field=models.CharField(max_length=133, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='location_en',
            field=models.CharField(max_length=43, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='location_ru',
            field=models.CharField(max_length=43, null=True),
        ),
        migrations.AddField(
            model_name='apartmentbonus',
            name='bonus_name_en',
            field=models.CharField(max_length=143, null=True),
        ),
        migrations.AddField(
            model_name='apartmentbonus',
            name='bonus_name_ru',
            field=models.CharField(max_length=143, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
    ]
